#!/usr/bin/env ruby
path = ENV["GITROCIOUS_FILE_LOCATION"]
require APP_PATH = File.expand_path('#{path}/config/application',  __FILE__)
require File.expand_path('#{path}/config/boot',  __FILE__)

Rails.env="production"
Rails.application.require_environment!

(ref_name, old_rev, new_rev) = ARGV

repo = Repo.find_by_name(ENV["GITROCIOUS_REPO_NAME"])

key = Key.includes(:user).find(ENV["GITROCIOUS_USER_KEY"])
user = key.user

if(!UserRepoPermission.check_permissions(user.id,repo.id,ref_name))
	if(!GroupRepoPermission.check_permissions(user.groups.ids,repo.id,ref_name)
		abort("Permission denied to repository: #{repo.name}")
	end
end
