# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26c87bf7df22ed198c67b106a79d4d84ef1a015f75d31f8ad204cad9e427381b400996bdb79d3b1f48c5bcf52fd61da649cd6f6435f55549de9d9994276c94d6

test:
  secret_key_base: c0166f28fce8eb28f9dfafae8718fbe13e5c4dccd8e507b68862766d4e8ba702f23b05b037b252598b67abbeb1799af9f5dec938a79f0da591c5a9cfdcaeece2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
